version: "3.3"

services:

  server:
    build: ./backend
    container_name: server
    ports:
      - "8080:8080"
    networks: 
      - base
    volumes:
      - ./backend:/app
    restart: always

networks:
  base:

    